name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Запуск тестов
      run: |
        pytest
